server:
  port: 8673
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NativeCreater-Liu/spring-cloud-config
          search-paths: /**
      label: master
      username: 15300385727@163.com
      password: cheng2ni1sheng@
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

